server:
  port: 8888
management:
  security:
    enabled: false
spring:
  profiles:
    active: subversion
  cloud:
    config:
      server:
        svn:
          uri: https://localhost/svn/config-project
          username: admin
          password: 123456
        default-label: test-label